const topics = [
  { title: 'The pipeline cast', text: 'A trigger starts a pipeline. A pipeline is organised into stages; stages contain jobs; jobs contain tasks. Build output can become artifacts, which later stages or deployments consume.', detail: 'An agent is the execution software and runs one job at a time. The job is the unit assigned to an agent. A stage is a logical boundary such as build, test, or deploy, and a pipeline can repeat this flow after each code change.', trap: 'Do not say an agent runs a whole pipeline. It runs a job; a pipeline can involve several jobs and agents.', tip: 'Memory chain: trigger -> pipeline -> stage -> job -> task -> artifact -> target.' },
  { title: 'Agent choice', text: 'Microsoft-hosted means a fresh Microsoft-managed VM for each run, automatic maintenance, and job time limits. Self-hosted means you manage the machine and software, with more control and no job time limit.', detail: 'Microsoft-hosted agents reduce maintenance and start clean, but the VM is discarded after the run. Self-hosted agents can keep tools, caches, and dependencies, but you own patching, capacity, security, and reliability. Self-hosted agents can run on Linux, macOS, Windows, or Linux Docker containers.', trap: 'Self-hosted does not mean Azure DevOps stops managing the pipeline. It means you manage the agent machine and its environment.', tip: 'Choose self-hosted for custom software, private networks, persistent dependencies, or builds longer than hosted limits.' },
  { title: 'Four job types', text: 'Agent pool jobs run on a pool agent. Container jobs run inside a container on an agent. Deployment group jobs target registered machines. Agentless (server) jobs run on Azure DevOps itself.', detail: 'Container jobs still need a host agent. Deployment group jobs are useful for deploying to several target machines, such as a web-server farm. Agentless jobs suit approvals, REST API calls, and Azure Function executions that do not need a build environment.', trap: 'A container job is not agentless: the container runs on an agent from an agent pool.', tip: 'Ask: does this job need a machine, a container, target machines, or no agent?' },
  { title: 'What a pool means', text: 'A pool organises agents and defines their sharing boundary. Organisation pools can be shared across projects; project pools are limited to a project unless linked to an organisation pool.', detail: 'When authoring a build or release pipeline, you specify the pool the job should use. A project agent pool can point to an organisation agent pool, so the same machines can serve selected projects. Access can be granted to all pipelines when a pool is created.', trap: 'A pool is not a single machine and it is not automatically available to every project just because it exists.', tip: 'A pool is the team or organisation shelf that agents sit on.' },
  { title: 'The predefined pool', text: 'The Azure Pipelines pool provides Microsoft-hosted agents without you configuring build infrastructure. Images change over time, so check Microsoft documentation for the current operating systems and installed software.', detail: 'All project contributors are normally assigned the User role on hosted pools, allowing them to author and run build and release pipelines using Microsoft-hosted agents. The module lists Windows and Linux images plus macOS images, but the current image list is maintained separately by Microsoft.', trap: 'Do not memorise the old image list as permanent. Know what the predefined pool provides and where to check the current images.', tip: 'YAML pipelines keep CI/CD definitions with the code; either YAML or classic pipelines still need an agent to run work.' },
  { title: 'Which pool scenario?', text: 'Team-specific: one team owns the machines. Organisation-wide: infrastructure shares with every project. Selective sharing: only named projects link to the organisation pool.', detail: 'Team-specific setup creates a project pool and a new organisation pool for that team. Organisation-wide setup can auto-provision corresponding project pools for existing and future projects. Selective sharing creates links only in chosen projects. Creating organisation pools requires Administrator access in All Pools.', trap: 'Selective sharing is not the same as giving every project its own agents. The projects can share the same organisation pool while access remains limited.', tip: 'The scope is the decision: one team, everyone, or a chosen set.' },
  { title: 'The agent pulls', text: 'The agent initiates HTTPS communication. After registration it gets a listener OAuth token, polls for jobs, receives a job-specific token, runs the job, discards that token, and polls again.', detail: 'The agent always initiates the connection, which supports agents behind firewalls and avoids Azure Pipelines needing to open an inbound connection. The server encrypts job payloads with the agent public key; the agent decrypts them with its private key. Secrets remain protected during communication.', trap: 'The model is pull, not push: Azure Pipelines does not log into the agent to start work.', tip: 'Pull model: the agent asks Azure Pipelines for work.' },
  { title: 'Network line of sight', text: 'For deployment, the agent must reach the target server and Azure Pipelines. Microsoft-hosted agents usually reach Azure resources; on-premises targets behind firewalls usually need a self-hosted agent inside that network.', detail: 'Line of sight means network connectivity, not visual access. A self-hosted agent needs connectivity to the target environment and Internet access to Azure Pipelines or Azure DevOps Server. Place it where both connections are possible and configure firewalls accordingly.', trap: 'An agent that can reach Azure DevOps but cannot reach the target cannot deploy successfully.', tip: 'Place the agent where it can see both sides: Azure DevOps and the target.' },
  { title: 'Security and operations', text: 'Registration needs an agent-pool administrator and local administrator rights. A PAT is used only during registration. Service mode is normally recommended; interactive mode is for cases such as UI tests and has physical security risks.', detail: 'Service mode starts after reboots and is managed by the operating system. Interactive mode may be needed when a browser or UI test must run in the logged-in agent account; auto-logon and disabled screen savers increase physical-security risk. Minor agent updates can be automatic, major updates need manual work, and interactive agents require manual upgrades. Multiple agents on one machine can cause disk, I/O, and shared-dependency conflicts.', trap: 'The registration administrator identity is not retained for ongoing communication. The PAT is not the agent’s permanent communication credential.', tip: 'Organisation roles: Reader, Service Account, Administrator. Project roles: Reader, User, Administrator.' },
  { title: 'Continuous integration', text: 'CI means integrating small code changes frequently and automatically building and testing them.', detail: 'A healthy CI pipeline gives rapid feedback on pull requests or commits: checkout, restore dependencies, compile, unit test, lint, security scan, and publish useful results. CI does not mean production deployment; it means the change is validated and produces trustworthy output.', trap: 'A green build proves only what your automated checks cover. It is not proof that every production behaviour is safe.', tip: 'CI answers: can we integrate this change into the shared codebase safely?' },
  { title: 'Delivery versus deployment', text: 'Continuous delivery keeps every passing change ready to release. Continuous deployment automatically sends passing changes to production.', detail: 'Delivery can include a manual approval, a release window, or a business decision before production. Deployment removes that routine manual step when automated safeguards are strong enough. Both need reliable tests, versioned artifacts, observability, and a rollback or forward-fix plan.', trap: 'Continuous delivery is not the same as continuous deployment. “Deployable” does not mean “already in production.”', tip: 'Delivery means ready; deployment means automatically released.' },
  { title: 'One build, one artifact', text: 'Build an immutable versioned artifact once, then promote that same artifact through environments.', detail: 'For a microservice package, record source commit, service versions, dependencies, configuration schema, migrations, and test evidence in release metadata. Rebuilding separately for staging and production can create a different binary from the one you tested.', trap: 'Do not compile a fresh production build from the same branch and assume it is identical to staging.', tip: 'Build once. Test the artifact. Promote the artifact.' },
  { title: 'Microservice release trains', text: 'A platform with many services needs an explicit decision about independent releases versus one coordinated package.', detail: 'Independent deployment gives speed but requires backwards-compatible APIs, consumer-driven contract tests, compatibility windows, and service ownership. A fortnightly platform package gives coordination and a clear customer version, but it can make one slow service hold back everything. Many teams use both: services deploy independently internally, while a tested compatibility bundle is published externally.', trap: 'Microservices do not automatically mean independent releases. Architecture and release policy are separate decisions.', tip: 'Choose the smallest release unit that your contracts and customers can safely support.' },
  { title: 'Environments and promotion', text: 'Environments are controlled destinations such as integration, QA, pre-production, and production; promotion moves a tested artifact between them.', detail: 'Keep environment configuration separate from the artifact, protect production permissions, and make promotion visible and auditable. Environment checks can include approvals, business hours, security gates, health checks, and required reviewers.', trap: 'An environment is more than a server name: it is a controlled boundary with access, configuration, data, and evidence.', tip: 'The artifact stays the same; the environment supplies its settings and safeguards.' },
  { title: 'Testing the path to production', text: 'Different tests answer different risk questions: unit, integration, contract, end-to-end, smoke, performance, and security tests.', detail: 'Fast tests belong early for quick feedback. Contract tests are especially valuable for microservices because they check that a provider and its consumers agree. End-to-end tests should cover critical journeys, not every internal detail. Smoke tests confirm the deployment is alive; deeper checks confirm it is correct.', trap: 'More end-to-end tests do not automatically mean more confidence if they are slow, flaky, or poorly targeted.', tip: 'Use a testing pyramid: many fast checks, fewer expensive full-system checks.' },
  { title: 'Safe deployment strategies', text: 'Rolling, blue-green, canary, and feature flags reduce the blast radius of a change.', detail: 'Rolling replaces instances gradually. Blue-green keeps two environments and switches traffic. Canary sends a small percentage of traffic to the new version. Feature flags separate code deployment from feature activation and can support gradual exposure.', trap: 'A deployment strategy is not a rollback plan by itself. You still need detection, decision thresholds, and a recovery action.', tip: 'Reduce how many users and services can be affected before confidence is earned.' },
  { title: 'Rollback and forward fix', text: 'A rollback restores a previous known-good version; a forward fix deploys a new version that corrects the problem.', detail: 'Rollback is easier when artifacts are immutable, database changes are backwards compatible, migrations are observable, and the previous version remains available. For data changes, reverting application code may not revert data. Sometimes a forward fix is safer than rollback.', trap: '“Just roll back” is not a complete plan for an irreversible schema or data migration.', tip: 'Plan recovery before release: who decides, what signal triggers it, and what action is safe?' },
  { title: 'Observability and release health', text: 'Logs explain events, metrics show system behaviour, and traces show a request across services.', detail: 'For an iGaming platform, release health might include error rate, latency, throughput, dependency failures, queue depth, customer-impacting transaction success, and business-specific settlement or account signals. Compare canary metrics with the stable version and define thresholds before deployment.', trap: 'A pipeline being green does not mean production is healthy. Build success and runtime health are different signals.', tip: 'Release engineering closes the loop with telemetry, not just a successful deploy step.' },
  { title: 'Governance without a bottleneck', text: 'Good controls make risk visible and repeatable without turning every release into a meeting.', detail: 'Use automated evidence, clear ownership, protected branches, least-privilege service connections, separation of duties where required, and approvals only at meaningful risk boundaries. A two-week package can have a predictable release window while urgent low-risk fixes use a smaller path.', trap: 'Adding a manual approval to every stage does not automatically improve safety; it can hide weak automation and slow feedback.', tip: 'Automate evidence; reserve human judgement for decisions machines cannot make.' },
  { title: 'The release manager as system designer', text: 'Your role is to make the flow of change visible, measurable, and improvable.', detail: 'Ask where work waits, how long feedback takes, which checks catch defects, how packages are identified, who owns each service, how a release is approved, and how customers learn about risk. You do not need to write every task, but you need to understand the control points well enough to challenge them.', trap: 'Release management is not just scheduling deployments. It is designing a reliable path from change to value.', tip: 'Measure lead time, deployment frequency, change failure rate, and time to restore service.' }
];

const cards = [
  ['What does an agent do?', 'An installable program that runs one build or deployment job at a time.'],
  ['What is the biggest Microsoft-hosted trade-off?', 'It is easy and fresh each run, but job time limits apply and the VM is discarded afterward.'],
  ['When is self-hosted a good choice?', 'When you need custom software, private network access, persistent dependencies, or no job time limit.'],
  ['What is an agent pool?', 'A group that organizes agents and defines the boundary over which they can be shared.'],
  ['Name all four job types.', 'Agent pool, container, deployment group, and agentless/server jobs.'],
  ['What does an agentless job need?', 'No build agent. It runs on Azure DevOps for work such as approvals, REST calls, or Azure Functions.'],
  ['Who can register an agent?', 'Someone who is an agent-pool administrator and a local administrator on the server.'],
  ['When is a self-hosted agent needed for deployment?', 'When it must reach an on-premises target that a Microsoft-hosted agent cannot reach through the firewall.'],
  ['What is the communication model?', 'Pull: the agent initiates HTTPS communication and polls Azure Pipelines for work.'],
  ['What is a PAT used for?', 'Agent registration only; it is not retained for ongoing communication.'],
  ['Service or interactive mode?', 'Service mode is recommended for most production cases; interactive mode suits UI tests but creates security risks.'],
  ['What changes between organization and project pool roles?', 'Organization roles include Reader, Service Account, Administrator; project roles include Reader, User, Administrator.']
  ,['What is the difference between a stage, job, task, and agent?', 'A stage groups work, a job is assigned for execution, tasks are the individual steps, and an agent runs one job at a time.']
  ,['Why does a clean Microsoft-hosted VM matter?', 'It reduces contamination between runs and maintenance work, but it also removes caches and installed dependencies after the run.']
  ,['Why can a container job still require an agent?', 'The container needs an agent host to run it; containerisation changes the job environment, not the need for compute.']
  ,['What is the difference between a project pool and an organisation pool?', 'An organisation pool can provide a sharing boundary across projects; a project pool is scoped to a project and can link to an organisation pool.']
  ,['What does All Pools control?', 'It controls inherited security for organisation agent pools and, in the project context, project agent pools.']
  ,['What are the organization pool roles?', 'Reader views the pool and agents; Service Account can use it to create a project pool; Administrator can manage agents, memberships, and registration.']
  ,['What are the project pool roles?', 'Reader views the pool; User can use it when authoring pipelines; Administrator can manage its role membership and operations.']
  ,['What are the two identities involved in registration?', 'The registering person needs pool Administrator and local Administrator rights. That identity is only needed for setup, not ongoing agent communication.']
  ,['Why is service mode usually preferred?', 'It starts reliably after restarts, is managed by the OS, and has a better automatic-upgrade experience.']
  ,['When might interactive mode be necessary?', 'For UI tests such as Selenium or Coded UI, where the browser launches in the context of the logged-in agent account.']
  ,['What are the risks of multiple agents on one machine?', 'Resource contention, disk and I/O conflicts, singleton tool conflicts, and unreliable results when parallel jobs share dependencies.']
  ,['What is YAML pipeline as code?', 'The pipeline definition lives with the application code in the repository and supports features such as pull requests, reviews, history, branches, and templates.']
  ,['What does continuous integration mean?', 'Integrating small changes frequently and automatically building and testing them to get fast feedback.']
  ,['What is continuous delivery?', 'Every passing change is kept in a deployable state, but production may still require an approval or business decision.']
  ,['What is continuous deployment?', 'Every change that passes the automated safeguards is automatically deployed to production.']
  ,['Why build one artifact and promote it?', 'The artifact tested in one environment is exactly the artifact deployed later; rebuilding can produce a different result.']
  ,['What release decision matters for microservices?', 'Whether services deploy independently or travel as a coordinated, tested package, based on contracts and customer needs.']
  ,['What is a release train?', 'A coordinated package or cadence in which a set of compatible service versions is tested and released together.']
  ,['What is a deployment environment?', 'A controlled destination with its own configuration, access, data, checks, and evidence, such as QA or production.']
  ,['What do contract tests protect?', 'They verify that a service provider and its consumers agree on the API or message contract.']
  ,['What does a smoke test prove?', 'That a deployment is alive and basic critical paths respond; it is not a complete correctness test.']
  ,['How does a canary deployment work?', 'A small percentage of traffic uses the new version first while telemetry is compared with the stable version.']
  ,['What is the difference between blue-green and rolling?', 'Blue-green switches between two environments; rolling replaces instances gradually in the same service fleet.']
  ,['Why use feature flags?', 'To separate deploying code from activating a feature, allowing gradual exposure or a quick disable without redeploying.']
  ,['Why might a forward fix be safer than rollback?', 'A database or data change may be irreversible, so a new compatible version can be safer than returning to old code.']
  ,['What do logs, metrics, and traces tell you?', 'Logs describe events, metrics show behaviour over time, and traces follow a request across services.']
  ,['Name four useful delivery metrics.', 'Lead time for changes, deployment frequency, change failure rate, and time to restore service.']
  ,['What should a release manager automate?', 'Evidence, repeatable checks, versioning, notifications, and routine promotion steps, reserving judgement for meaningful risk decisions.']
  ,['What is the safest response to a slow pipeline?', 'Find where work waits or feedback is slow, then improve the bottleneck rather than adding approval steps blindly.']
  ,['Why are backward-compatible APIs important?', 'They let different microservice versions coexist while services are deployed at different times.']
  ,['What should release metadata include?', 'The source commit, service versions, dependencies, configuration or migration information, and test evidence.']
];

const questions = [
  { q:'Your build needs a private tool installed and must access an on-premises server behind a firewall. Which agent?', options:['Microsoft-hosted','Self-hosted','Agentless'], answer:1, why:'Self-hosted gives you control of software and network placement.' },
  { q:'Which job type is best for an approval or REST API call that needs no build environment?', options:['Container job','Deployment group job','Agentless/server job'], answer:2, why:'Agentless jobs run directly on Azure DevOps.' },
  { q:'What happens after an agent finishes a job?', options:['It keeps the job token forever','It discards the job token and polls again','The server logs into the agent'], answer:1, why:'The job-specific OAuth token is discarded; the listener token is used to keep monitoring.' },
  { q:'You need a pool shared by three projects but not the rest of the organization. What is the right pattern?', options:['A project pool in each project with separate agents','An organization pool linked only to those projects','The predefined Azure Pipelines pool'], answer:1, why:'Selective sharing links chosen project pools to one organization pool.' },
  { q:'Which statement about agent versions is correct?', options:['Major and minor upgrades are always automatic','Minor updates can be automatic; major updates need manual updates','Interactive agents always auto-upgrade'], answer:1, why:'Major versions require manual upgrades, and interactive agents require manual upgrades regardless.' }
  ,{ q:'Which statement best describes a job?', options:['The complete pipeline from trigger to deployment','A unit of work assigned to an agent','A group of projects that share a pool'], answer:1, why:'An agent runs one job at a time; a pipeline can contain multiple jobs.' }
  ,{ q:'A job must run with a fixed set of dependencies packaged into an image. Which type fits?', options:['Container job','Agentless job','Deployment group job'], answer:0, why:'Container jobs package the environment for consistency and isolation, while still using a host agent.' }
  ,{ q:'What is the key network property of the agent communication model?', options:['Azure DevOps opens inbound connections to every agent','The agent initiates HTTPS communication to Azure Pipelines','The target server polls the pipeline directly'], answer:1, why:'The pull model lets an agent operate behind a firewall as long as it can make outbound connections.' }
  ,{ q:'A company wants all current and future projects to receive a corresponding project pool. Which setup?', options:['Selective sharing','Organization-wide pool with auto-provisioning','A separate self-hosted agent per project'], answer:1, why:'The organization-wide scenario can auto-provision project pools for existing and future projects.' }
  ,{ q:'Which permission is needed to author a pipeline using a project agent pool?', options:['Project pool User','Organization pool Service Account','Local server Administrator only'], answer:0, why:'The project pool User role allows members to use the pool when authoring pipelines.' }
  ,{ q:'Which statement about a PAT is correct?', options:['It is stored and used for every job','It is only required during agent registration','It replaces the listener OAuth token'], answer:1, why:'The PAT authenticates registration; it is not retained for ongoing communication.' }
  ,{ q:'A deployment agent can reach Azure DevOps but not the private target server. What is the result?', options:['Deployment succeeds because the server pulls the artifact','Deployment fails because the agent lacks line of sight','Azure Pipelines automatically opens the firewall'], answer:1, why:'The agent must have connectivity to both Azure Pipelines and the target environment.' }
  ,{ q:'Why should you be cautious about running several agents on one machine?', options:['Agents cannot run concurrently','Builds can compete for resources and shared dependencies','Only Microsoft-hosted agents support parallel work'], answer:1, why:'Parallel self-hosted agents can contend for disk, I/O, tools, and singleton dependencies.' }
  ,{ q:'Which role can use an organization pool to create a project agent pool?', options:['Organization Reader','Organization Service Account','Project Reader'], answer:1, why:'The organization Service Account role is intended for using the organization pool to create a project pool.' }
  ,{ q:'Which statement best describes continuous delivery?', options:['Every commit is automatically in production','Every passing change is kept deployable, with production possibly requiring approval','Only production incidents are tested'], answer:1, why:'Delivery means production-ready and repeatable; deployment is the separate act of sending it to production.' }
  ,{ q:'Which statement best describes continuous deployment?', options:['A human approves every production change','Passing changes are automatically deployed to production','Developers merge code once every two weeks'], answer:1, why:'Continuous deployment removes the routine manual production release step when safeguards pass.' }
  ,{ q:'Why should staging and production use the same built artifact?', options:['It makes the artifact smaller','It ensures the thing tested is the thing deployed','It removes the need for monitoring'], answer:1, why:'Rebuilding can change the binary or dependency set, weakening confidence in test evidence.' }
  ,{ q:'Your services have independent teams but incompatible API changes are common. What should come first?', options:['Deploy independently immediately','Improve compatibility and contract testing','Add a second production database'], answer:1, why:'Independent deployment depends on compatible contracts and tests that detect provider-consumer breakage.' }
  ,{ q:'What is the main purpose of an environment check or approval?', options:['To make every pipeline step manual','To protect a meaningful boundary such as production with explicit evidence or judgement','To replace automated tests'], answer:1, why:'Controls should sit at risk boundaries and complement automation, not replace it everywhere.' }
  ,{ q:'Which test is especially valuable for microservice API compatibility?', options:['Consumer-driven contract test','A screenshot comparison only','A manual release meeting'], answer:0, why:'Contract tests verify that a provider still satisfies the expectations of its consumers.' }
  ,{ q:'A canary release shows a higher error rate than the stable version. What should happen?', options:['Increase traffic immediately','Use the predefined threshold and pause or recover','Ignore it until the fortnightly package'], answer:1, why:'Canaries are useful because telemetry can stop a rollout before the whole user base is affected.' }
  ,{ q:'What does a feature flag allow?', options:['A database backup to run faster','Code to be deployed separately from feature activation','An agent to avoid registration'], answer:1, why:'Flags let teams expose, disable, or gradually roll out a capability without necessarily redeploying code.' }
  ,{ q:'Why is rollback not always safe after a database migration?', options:['Old code may not understand the changed schema or data','Pipelines cannot deploy databases','Hosted agents cannot run SQL'], answer:0, why:'Application rollback does not automatically undo irreversible data changes; a forward fix may be safer.' }
  ,{ q:'Which signal best tells you whether a new version is harming production?', options:['Only that the pipeline is green','Runtime telemetry such as error rate, latency, and transaction success','The number of YAML lines'], answer:1, why:'Build success and runtime health are different signals; production telemetry closes the loop.' }
  ,{ q:'Which is a DORA-style delivery metric?', options:['Change failure rate','Number of agent pool readers','Lines in a release note'], answer:0, why:'Change failure rate measures how often deployments cause a failure or require remediation.' }
  ,{ q:'What is a good first question when a release process is too slow?', options:['Where does work wait and where is feedback slow?','Which approval can we add?','Can we rebuild the artifact more times?'], answer:0, why:'Improvement starts by locating the bottleneck, then reducing queue time and feedback time.' }
  ,{ q:'A service is part of a coordinated fortnightly package. What should make the package traceable?', options:['A version and release manifest listing commits, service versions, and evidence','Only the date in a calendar','A shared verbal agreement'], answer:0, why:'A release manifest creates an auditable link between the customer package and its contents.' }
  ,{ q:'Which deployment strategy sends a small percentage of users to a new version first?', options:['Canary','Big bang','Agentless'], answer:0, why:'Canary reduces blast radius and uses telemetry before wider exposure.' }
  ,{ q:'What is the release manager’s technical responsibility?', options:['Write every service’s code','Understand and improve the control points from change to production','Approve every task manually'], answer:1, why:'Release engineering is system design: flow, evidence, ownership, safety, and improvement.' }
];

const state = JSON.parse(localStorage.getItem('pipelineStudy') || '{"done":[],"known":[],"score":null,"lastStudy":null}');
const save = () => localStorage.setItem('pipelineStudy', JSON.stringify(state));
const $ = id => document.getElementById(id);

function renderTopics() {
  $('topicGrid').innerHTML = topics.map((topic, index) => `<article class="topic ${state.done.includes(index) ? 'is-done' : ''}"><span class="topic-number">0${index + 1}</span><h3>${topic.title}</h3><p>${topic.text}</p><details><summary>Open exam detail</summary><p class="topic-detail">${topic.detail}</p><p class="topic-trap"><strong>Common trap:</strong> ${topic.trap}</p></details><span class="topic-tip">${topic.tip}</span><button data-topic="${index}" type="button">${state.done.includes(index) ? 'Mark for review' : 'Mark complete'}</button></article>`).join('');
  document.querySelectorAll('[data-topic]').forEach(button => button.addEventListener('click', () => { const index = Number(button.dataset.topic); state.done = state.done.includes(index) ? state.done.filter(item => item !== index) : [...state.done, index]; state.lastStudy = new Date().toISOString().slice(0,10); save(); renderTopics(); updateProgress(); }));
}
function updateProgress() { const count = state.done.length; $('progressText').textContent = `${count} / ${topics.length} topics`; $('progressFill').style.width = `${count / topics.length * 100}%`; $('progressMessage').textContent = count === 0 ? 'No pressure. One topic is enough for today.' : count === topics.length ? 'You have the map. Use the cards to make it stick.' : `${topics.length - count} topics left. A tiny session still counts.`; $('quizScore').textContent = state.score === null ? '' : `Last quiz: ${state.score}/${questions.length}`; $('streakLabel').textContent = state.lastStudy === new Date().toISOString().slice(0,10) ? 'Studying today' : '0 days'; }

let cardIndex = 0;
let reviewQueue = [];
function cardKind(question) { if (/why|difference|versus|trade-off/i.test(question)) return 'Compare'; if (/how|what happens|what does/i.test(question)) return 'Explain'; if (/name|which|who/i.test(question)) return 'Recall'; return 'Define'; }
function cardHint(question, answer) { const words = question.replace(/[?]/g, '').split(' ').filter(word => word.length > 4); return `Start with: ${words.slice(0, 3).join(' ')}. Include the reason, not just the label.`; }
function cardContext(question) { if (/agent|pool|PAT|OAuth|job/i.test(question)) return 'This helps you choose the right Azure Pipelines control and explain it to an engineering team.'; if (/microservice|contract|API|service/i.test(question)) return 'This is how you make many services release safely without hiding dependencies between teams.'; if (/artifact|environment|version|manifest/i.test(question)) return 'This creates a traceable package that can be promoted consistently from testing to production.'; if (/deployment|canary|rollback|feature flag|blue-green/i.test(question)) return 'This reduces blast radius and gives your team a controlled response when production behaviour changes.'; if (/metric|slow|release manager|automate/i.test(question)) return 'This turns release engineering into an improvement system rather than a calendar of manual steps.'; return 'This connects the technical detail to a safer, faster path from change to customer.'; }
function nextCard() { cardIndex = reviewQueue.length ? reviewQueue.shift() : (cardIndex + 1) % cards.length; }
function renderCard() { const [question, answer] = cards[cardIndex]; $('cardQuestion').textContent = question; $('cardAnswer').textContent = answer; $('cardType').textContent = cardKind(question); $('cardContext').textContent = cardContext(question); $('hintBox').textContent = cardHint(question, answer); $('hintBox').hidden = true; $('hintButton').hidden = false; $('cardCount').textContent = `Card ${cardIndex + 1} of ${cards.length}`; $('reviewQueueLabel').textContent = reviewQueue.length ? `${reviewQueue.length} waiting for review` : ''; $('flashcard').classList.remove('is-flipped'); }
function showView(name) { document.querySelectorAll('.view').forEach(view => view.classList.toggle('is-visible', view.id === `${name}View`)); document.querySelectorAll('.tab').forEach(tab => tab.classList.toggle('is-active', tab.dataset.view === name)); if (name === 'cards') renderCard(); if (name === 'quiz') renderQuiz(); window.scrollTo({ top: document.querySelector('.tabs').offsetTop - 90, behavior:'smooth' }); }
function renderQuiz() { $('quizArea').innerHTML = `<div class="quiz-result"><h3>${questions.length} questions. No peeking.</h3><p>Choose an answer. The explanation matters more than the score. Aim for ${questions.length >= 10 ? 'at least 80%' : 'full marks'} before exam day.</p></div>` + questions.map((item, index) => `<article class="quiz-card" data-quiz="${index}"><h3>${index + 1}. ${item.q}</h3>${item.options.map((option, optionIndex) => `<button class="option" data-question="${index}" data-option="${optionIndex}" type="button">${option}</button>`).join('')}<p class="explanation" hidden></p></article>`).join(''); document.querySelectorAll('.option').forEach(button => button.addEventListener('click', answerQuiz)); }
function answerQuiz(event) { const button = event.currentTarget; const questionIndex = Number(button.dataset.question); const optionIndex = Number(button.dataset.option); const item = questions[questionIndex]; const card = document.querySelector(`[data-quiz="${questionIndex}"]`); if (card.dataset.answered) return; card.dataset.answered = 'true'; const correct = optionIndex === item.answer; button.classList.add(correct ? 'correct' : 'wrong'); card.querySelectorAll('.option')[item.answer].classList.add('correct'); const explanation = card.querySelector('.explanation'); explanation.innerHTML = correct ? `<strong>Correct.</strong> ${item.why}` : `<strong>Not quite.</strong> You chose <em>${item.options[optionIndex]}</em>. The correct answer is <em>${item.options[item.answer]}</em>. ${item.why}`; explanation.classList.toggle('is-wrong', !correct); explanation.hidden = false; card.dataset.correct = correct ? 'true' : 'false'; const answered = [...document.querySelectorAll('.quiz-card[data-answered]')]; if (answered.length === questions.length) { state.score = answered.filter(item => item.dataset.correct === 'true').length; state.lastStudy = new Date().toISOString().slice(0,10); save(); updateProgress(); const result = document.querySelector('.quiz-result'); result.innerHTML = `<h3>You scored ${state.score}/${questions.length}.</h3><p>${state.score >= Math.ceil(questions.length * .8) ? 'Strong retrieval. Revisit the cards you missed.' : 'That is useful information. Read the explanations, then try the cards once.'}</p>`; } }

document.querySelectorAll('.tab').forEach(tab => tab.addEventListener('click', () => showView(tab.dataset.view)));
$('startButton').addEventListener('click', () => { showView('learn'); document.querySelector('.topic').scrollIntoView({ behavior:'smooth', block:'center' }); });
$('flashcard').addEventListener('click', () => $('flashcard').classList.toggle('is-flipped'));
$('flashcard').addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); $('flashcard').classList.toggle('is-flipped'); } });
$('hintButton').addEventListener('click', event => { event.stopPropagation(); $('hintBox').hidden = false; $('hintButton').hidden = true; });
$('knownButton').addEventListener('click', () => { if (!state.known.includes(cardIndex)) state.known.push(cardIndex); nextCard(); save(); renderCard(); });
 $('againButton').addEventListener('click', () => { const retryIndex = cardIndex; reviewQueue.push(retryIndex); cardIndex = (cardIndex + 1) % cards.length; renderCard(); });
$('shuffleButton').addEventListener('click', () => { cardIndex = Math.floor(Math.random() * cards.length); renderCard(); });
$('resetButton').addEventListener('click', () => { if (window.confirm('Reset all study progress?')) { localStorage.removeItem('pipelineStudy'); window.location.reload(); } });
renderTopics(); updateProgress(); renderCard();
